codecov:
  notify:
    require_ci_to_pass: yes
comment:
  layout: header, changes, diff
coverage:
  status:
    patch:
      default:
        target: '10'
    project:
      default:
        target: auto
